export default {
    bgColor:'#e7c18b',
    loginlogoutbutton:'blue',
    statusbarcolor:'#e7c18b',
    bgcolorSign_up_in:'#95cca4',
    RegisterandLoginButton:'green',
    gradientForm: '#A376F1',
    primary: '#7d5fff',
    white: '#FFFFFF',
    dark: '#444',
    warning: '#f0d500',
    danger: '#FF0D0E',
    gray: '#666666',
    grayLight: '#ccc',
    black: '#0a0a0a',
}